In [1]:
import numerical_solver
import numpy as np
import pde

In [2]:
def f(x):
    return np.sin(np.pi * x)
def a(x):
    return 1
x = np.linspace(0, 1, 11)
equation = pde.PoissonEquation1D(a, f, "Dirichlet", x)
solver = numerical_solver.MultigridSolver(equation)
# print(equation.A)
# print(f"The true solution is {f(x)/(np.pi**2)}")
# # print(solver.restrictor)
# print(solver.interpolator)
solver.iteration(np.zeros_like(equation.b))

Pre-smoothing
Max iterations reached without convergence.
Computing residual
Restricting residual
Solving on coarser grid
Max iterations reached without convergence.
Prolongating solution to fine grid
Updating solution
Post-smoothing
Max iterations reached without convergence.


array([0.        , 0.01627164, 0.03077026, 0.04259971, 0.04978733,
       0.05265614, 0.04978733, 0.04259971, 0.03077026, 0.01627164,
       0.        ])

In [3]:
def f(x, y):
    return np.sin(np.pi * x) * np.sin(np.pi * y)
def a(x, y):
    return 1
x = np.linspace(0, 1, 7)
y = np.linspace(0, 1, 7)
equation2d = pde.PoissonEquation2D(a, f, "Periodic", x, y)
print(equation2d.A[9].reshape((7, 7)))
u_exact_2d = (1/(2*np.pi**2)) * np.sin(np.pi * x[:, None]) * np.sin(np.pi * y[None, :])
print(f"The true 2D solution is {f(x[:, None], y[None, :])/(2*np.pi**2)}")
print(f"The numeric 2D solution is {equation2d.solve()}")
print(f"error norm is {np.linalg.norm(equation2d.solve() - f(x[:, None], y[None, :])/(2*np.pi**2))}")
print(equation2d.A.reshape((7, 7, 7,7))[1, 1])


[[  0.   0. -36.   0.   0.   0.   0.]
 [  0. -36. 144. -36.   0.   0.   0.]
 [  0.   0. -36.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.]]
The true 2D solution is [[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.26651480e-02 2.19366797e-02 2.53302959e-02
  2.19366797e-02 1.26651480e-02 3.10206658e-18]
 [0.00000000e+00 2.19366797e-02 3.79954439e-02 4.38733595e-02
  3.79954439e-02 2.19366797e-02 5.37293693e-18]
 [0.00000000e+00 2.53302959e-02 4.38733595e-02 5.06605918e-02
  4.38733595e-02 2.53302959e-02 6.20413316e-18]
 [0.00000000e+00 2.19366797e-02 3.79954439e-02 4.38733595e-02
  3.79954439e-02 2.19366797e-02 5.37293693e-18]
 [0.00000000e+00 1.26651480e-02 2.19366797e-02 2.53302959e-02
  2.19366797e-02 1.26651480e-02 3.10206658e-18]
 [0.00000000e+00 3.10206658e-18 5.37293693e-18 6.

In [4]:
solver2d = numerical_solver.MultigridSolver(equation2d)
solver2d.iteration(np.zeros_like(equation2d.b)).reshape((7, 7))


Pre-smoothing
Max iterations reached without convergence.
Computing residual
Restricting residual
Solving on coarser grid
Max iterations reached without convergence.
Prolongating solution to fine grid
Updating solution
Post-smoothing
Max iterations reached without convergence.


array([[0.02575932, 0.0286781 , 0.03255807, 0.03434411, 0.03255807,
        0.0286781 , 0.02575932],
       [0.0286781 , 0.03474141, 0.04165558, 0.04459088, 0.04165558,
        0.03474141, 0.0286781 ],
       [0.03255807, 0.04165558, 0.05145668, 0.05560426, 0.05145668,
        0.04165558, 0.03255807],
       [0.03434411, 0.04459088, 0.05560426, 0.06015918, 0.05560426,
        0.04459088, 0.03434411],
       [0.03255807, 0.04165558, 0.05145668, 0.05560426, 0.05145668,
        0.04165558, 0.03255807],
       [0.0286781 , 0.03474141, 0.04165558, 0.04459088, 0.04165558,
        0.03474141, 0.0286781 ],
       [0.02575932, 0.0286781 , 0.03255807, 0.03434411, 0.03255807,
        0.0286781 , 0.02575932]])

In [6]:
for i in range(solver2d.interpolator.shape[1]):
    print(solver2d.interpolator[:, i].reshape((7, 7)))

[[1.   0.5  0.   0.   0.   0.   0.5 ]
 [0.5  0.25 0.   0.   0.   0.   0.25]
 [0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.  ]
 [0.5  0.25 0.   0.   0.   0.   0.25]]
[[0.   0.5  1.   0.5  0.   0.   0.  ]
 [0.   0.25 0.5  0.25 0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.25 0.5  0.25 0.   0.   0.  ]]
[[0.   0.   0.   0.5  1.   0.5  0.  ]
 [0.   0.   0.   0.25 0.5  0.25 0.  ]
 [0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.25 0.5  0.25 0.  ]]
[[0.5  0.   0.   0.   0.   0.5  1.  ]
 [0.25 0.   0.   0.   0.   0.25 0.5 ]
 [0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.